// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf_5XVEJ-EUacw40IU5vhFc01CFU9IdSM',
    appId: '1:415382259904:web:d9bda025f82fb4b5d24525',
    messagingSenderId: '415382259904',
    projectId: 'weatherapp-87df4',
    authDomain: 'weatherapp-87df4.firebaseapp.com',
    storageBucket: 'weatherapp-87df4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANmxrFjbg5Ze7tVJaqACFrLDCKQhQraYc',
    appId: '1:415382259904:android:0845471c2c7a1de7d24525',
    messagingSenderId: '415382259904',
    projectId: 'weatherapp-87df4',
    storageBucket: 'weatherapp-87df4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVhp2DuvTN9H51I3-XOdgl4CGYLAjVEts',
    appId: '1:415382259904:ios:37cc49cd93962db5d24525',
    messagingSenderId: '415382259904',
    projectId: 'weatherapp-87df4',
    storageBucket: 'weatherapp-87df4.appspot.com',
    iosBundleId: 'com.example.weatherAppTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVhp2DuvTN9H51I3-XOdgl4CGYLAjVEts',
    appId: '1:415382259904:ios:37cc49cd93962db5d24525',
    messagingSenderId: '415382259904',
    projectId: 'weatherapp-87df4',
    storageBucket: 'weatherapp-87df4.appspot.com',
    iosBundleId: 'com.example.weatherAppTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf_5XVEJ-EUacw40IU5vhFc01CFU9IdSM',
    appId: '1:415382259904:web:5f14156bf1e349d0d24525',
    messagingSenderId: '415382259904',
    projectId: 'weatherapp-87df4',
    authDomain: 'weatherapp-87df4.firebaseapp.com',
    storageBucket: 'weatherapp-87df4.appspot.com',
  );
}
